export default [
  {
    path: '/login',
    layout: false,
    name: 'login',
    component: './login',
    hideInMenu: true,
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    icon: 'smile',
    component: './dashboard',
  },
  {
    name: 'app',
    icon: 'table',
    path: '/app',
    component: './app',
  },
  {
    name: 'appMonitor',
    icon: 'table',
    path: '/app/monitor',
    component: './app/monitor',
    hideInMenu: true,
  },
  {
    name: 'cacheKeys',
    icon: 'smile',
    path: 'cacheKeys',
    component: './cacheKeys',
    hideInMenu: true,
  },
  {
    name: 'cacheNames',
    icon: 'smile',
    path: 'cacheNames',
    component: './cacheNames',
    hideInMenu: true,
  },
  {
    name: 'cacheNamesMonitor',
    icon: 'table',
    path: '/cacheNames/monitor',
    component: './cacheNames/monitor',
    hideInMenu: true,
  },
  {
    name: 'cacheMetrics',
    icon: 'smile',
    path: 'cacheMetrics',
    component: './cacheMetrics',
    hideInMenu: true,
  },
  {
    name: 'cacheNodes',
    icon: 'smile',
    path: 'cacheNodes',
    component: './cacheNodes',
    hideInMenu: true,
  },
  {
    name: 'cacheNodesMonitor',
    icon: 'smile',
    path: '/cacheNodes/monitor',
    component: './cacheNodes/monitor',
    hideInMenu: true,
  },
  {
    name: 'logger',
    icon: 'smile',
    path: 'logger',
    component: './logger',
  },
  {
    name: 'user',
    icon: 'table',
    path: '/user',
    component: './user',
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  {
    component: './404',
  },
];
